configure.ac: fix cross compile error
On some distros, such as fedora32, cross compile failed
with following error since host library  is used.
undefined reference to `stat64@GLIBC_2.33'

According doc of ld, set searchdir begins with "=", but not hardcoded
locations.

Signed-off-by: Changqing Li <changqing.li@windriver.com>